export const APPLOADED_SUCCESS = 'APPLOADED_SUCCESS';

export const INIT_DATA_SUCCESS = 'INIT_DATA_SUCCESS';

export const DETAILS_SUCCESS = 'DETAILS_SUCCESS';

export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';


export const UPD_KEY_VALUE = 'UPD_KEY_VALUE';

export const UPD_KEY_VALUE_DIALOGS = 'UPD_KEY_VALUE_DIALOGS';

export const ISMOBILE_SUCCESS = 'ISMOBILE_SUCCESS';

export const SCREEN_SIZE = 'SCREEN_SIZE';

export const THUMBNAILBLOB = 'THUMBNAILBLOB';

export const THUMBNAILJSON = 'THUMBNAILJSON';

export const IMAGE_LIST_SUCCESS = 'IMAGE_LIST_SUCCESS';

 

export const PLAYING_SUCCESS = 'PLAYING_SUCCESS';

export const ISMUTE_SUCCESS = 'ISMUTE_SUCCESS';

export const VOLUME_SUCCESS = 'VOLUME_SUCCESS';

export const DURATION_SUCCESS = 'DURATION_SUCCESS';

export const CURRENTTIME_SUCCESS = 'CURRENTTIME_SUCCESS';

export const HOVER_SUCCESS = 'HOVER_SUCCESS';



export const CURRENT_PATH = 'CURRENT_PATH';

export const FORMS_SUCCESS = 'FORMS_SUCCESS';

export const FORMS_OBSERVES = 'FORMS_OBSERVES';

export const VALIDATIONFORMS_SUCCESS = 'VALIDATIONFORMS_SUCCESS';
